global:
  region: "asia-southeast1"
  state_bucket: "nasir-ck-tf-state"
  project_id: "nasir-482109"

network:
  vpc_name: "nasir-vpc" 
  auto_create_subnetworks: false
  description: "Nasir VPC"
  subnet_name: "subnet-asia-southeast1"
  subnet_ip: "10.0.0.0/16"
  subnet_description: "Nasir asia southeast 1"

management:
  instance_name: "management-vm"
  zone: "asia-southeast1-c"
  instance: "linux"
  instance_type: "n1-standard-1"
  disk_size_gb: 50
  disk_type: "pd-balanced"
  image: "ubuntu-os-cloud/ubuntu-2204-lts"
  create_internal_static_ip: true
  create_external_static_ip: true
  allow_stopping_for_update: true  

firewall-ssh:
  name: "gke-nasir-vpc-allow-ssh"
  description: "allow ssh"
  protocol: "tcp"
  ports: ["22"]
  source_ranges: ["0.0.0.0/0"]
  target_tags: ["management"]  

gke:
  name: "nasir-cluster"
  ip_range_pods: "sub-gke-pod"
  ip_range_services: "sub-gke-svc"
  cluster_description: "GKE Autopilot Cluster Nasir"
  kubernetes_version: "latest"
  release_channel: "REGULAR"  
  deletion_protection: false
  cluster_labels:
    environment: "lab"
    owner: "nasir"
  enable_private_nodes: true
  enable_private_endpoint: false
  master_ipv4_cidr_block: "10.0.0.0/0"
  master_global_access_enabled: false
  deploy_using_private_endpoint: false
  master_authorized_networks:
    - cidr_block: "0.0.0.0/0"
      display_name: "all" 
  http_load_balancing: true
  horizontal_pod_autoscaling: true
  dns_cache_enabled: true   
  enable_vertical_pod_autoscaling: false   
  logging_enabled_components: ["SYSTEM_COMPONENTS", "WORKLOADS"]
  monitoring_enabled_components: ["SYSTEM_COMPONENTS", "WORKLOADS"]
  enable_managed_prometheus: false       
  enable_shielded_nodes: true
  enable_binary_authorization: false  
  database_encryption:
    state: "GOOGLE_MANAGED_KEY"
  identity_namespace: "nasir-482109.svc.id.goog"
  maintenance_start_time: "03:00"
  maintenance_end_time: "04:00" 
  maintenance_recurrence: "FREQ=WEEKLY;BYDAY=SUN"
  maintenance_exclusions: []
  resource_usage_export_dataset_id: "gke_resource_usage_nasir"
  enable_network_egress_export: false
  enable_resource_consumption_export: false
  authenticator_security_group: ""
  network_project_id: "nasir-482109"  

artifact-registry:
  name: "nasir"  



